name: Test

on:
  repository_dispatch:
  workflow_dispatch:
  # schedule:
  #   - cron: 0 21 */7 * * 

env:
  userName: sec-an
  repoName: TV_Spider
  branchName: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      # - name: Check New Commit
      #   run: |
      #     upStream=https://github.com/${{ env.userName }}/${{ env.repoName }}
      #     echo "upStream=$upStream" >> $GITHUB_ENV
      #     commit=$(curl -sL $upStream/commits/${{ env.branchName }} |grep -o "/${{ env.userName }}/${{ env.repoName }}/commit/[a-z0-9]\+" |head -1 | cut -d\/ -f5)
      #     if ! git log --oneline |grep -q "$commit"; then
      #       echo "commit=$commit" >> $GITHUB_ENV
      #       echo "commitS=${commit:0:7}" >> $GITHUB_ENV
      #     fi
      # - name: Checkout Source Code and Zip
      #   if: ${{ env.commit }}
      #   run: |
      #     git clone ${{ env.upStream }} TVSP
      #     cd TVSP
      #     git checkout ${{ env.commit }}
      #     echo "tag=$(git log --date=format:'%Y%m%d-%H%M' --pretty=format:%cd ${{ env.commitS }} -1)" >> $GITHUB_ENV
      #     zip -q -x ".git/*" -r ${{ env.commitS }}-source.zip .

      # setup-qemu 如果您想使用 QEMU 添加仿真支持以便能够针对更多平台进行构建，则 action 会很有用
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      # setup-buildxaction 将默认使用docker-container 构建器驱动程序创建和引导构建器。非必需
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: |
            linux/386
            linux/amd64
            linux/arm/v7
            linux/arm64
          push: true
          file: PyDockerfile
          tags: |
            akvsdk/t4:latest
